# Generated by Django 5.0.1 on 2024-01-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
