# Generated by Django 5.0.1 on 2024-02-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_author_name_author_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
