# Generated by Django 5.0.1 on 2024-02-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
