# Generated by Django 5.0.1 on 2024-02-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='title',
            new_name='name',
        ),
    ]
